name: Build & Publish Telert (Docker + VS Code)

on:
  # ─── build Docker on every push to main AND on semver tags ────────────────
  push:
    branches: [ main ]
    tags:     [ "v*" ]
  workflow_dispatch:

jobs:
# ─────────────────────────────────────────────────────────────────────────────
# 1)  DOCKER  ─ build & push to GitHub Container Registry
# ─────────────────────────────────────────────────────────────────────────────
  build-and-publish-docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write   # needed so GITHUB_TOKEN can push to ghcr.io

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Extract Docker metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ghcr.io/${{ github.repository_owner }}/telert
        tags: |
          # semver tags when the workflow is triggered by a tag
          type=semver,pattern={{version}},enable={{is_tag}}
          type=semver,pattern={{major}}.{{minor}},enable={{is_tag}}

          # branch name for non-default branches
          type=ref,event=branch

          # commit SHA (short) – always
          type=sha,format=short

          # latest only on the default branch (main)
          type=raw,value=latest,enable={{is_default_branch}}
        flavor: |
          latest=auto

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags:   ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to:   type=gha,mode=max

# ─────────────────────────────────────────────────────────────────────────────
# 2)  VS CODE  ─ build & publish extension (only on semver tags or manual)
# ─────────────────────────────────────────────────────────────────────────────
  build-and-publish-vscode:
    runs-on: ubuntu-latest
    # run only when we’re on a tag or manual trigger
    if: github.event_name == 'workflow_dispatch' || startsWith(github.ref, 'refs/tags/v')

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Install vsce
      run: npm install -g @vscode/vsce

    # Extract / align extension version
    - name: Extract & sync version
      id: version
      run: |
        VERSION=$(node -p "require('./vscode-telert/package.json').version")

        # If triggered by a tag, make package.json match the tag
        if [[ "${GITHUB_REF}" == refs/tags/v* ]]; then
          TAG_VERSION="${GITHUB_REF#refs/tags/v}"
          if [[ "$VERSION" != "$TAG_VERSION" ]]; then
            echo "Syncing VS Code extension version → $TAG_VERSION"
            cd vscode-telert
            npm version "$TAG_VERSION" --no-git-tag-version
          fi
          echo "EXT_VERSION=$TAG_VERSION" >> $GITHUB_OUTPUT
        else
          echo "EXT_VERSION=$VERSION" >> $GITHUB_OUTPUT
        fi

    - name: Build & package extension
      run: |
        cd vscode-telert
        npm ci
        vsce package

    - name: Publish to VS Code Marketplace
      env:
        VSCE_PAT: ${{ secrets.VSCODE_MARKETPLACE_TOKEN }}
      run: |
        cd vscode-telert
        vsce publish -p "$VSCE_PAT"

    - name: Upload .vsix as artifact
      uses: actions/upload-artifact@v4
      with:
        name: telert-vscode-${{ steps.version.outputs.EXT_VERSION }}.vsix
        path: vscode-telert/telert-vscode-${{ steps.version.outputs.EXT_VERSION }}.vsix
